services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      CHAT_ID: ${CHAT_ID}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - data:/app/data
    networks:
      - tgcloud-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_WS_BASE_URL=${VITE_WS_BASE_URL}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - tgcloud-network
    restart: unless-stopped


networks:
  tgcloud-network:
    driver: bridge

volumes:
  data:
